name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      ksu_tag:
        description: KernelSU tag/branch
        required: true
        default: v3.1.0-legacy-susfs
  push:
    tags:
      - 'C-*'

env:
  KERNEL_CONFIG: alioth_stock-defconfig
  ARCH: arm64
  KERNEL_IMAGE_NAME: Image.gz-dtb

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3

      - name: Set swap
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: build-alioth
          max-size: 2G

      - name: Download toolchain
        run: |
          git clone https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone.git --depth 1 toolchain/llvm
          mkdir -p gcc-64
          curl -LSs "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz" | tar -C gcc-64 -zxvf -
          mkdir -p gcc-32
          curl -LSs "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz" | tar -C gcc-32 -zxvf -
          echo "$PWD/toolchain/llvm/bin" >> $GITHUB_PATH

      - name: Setup KernelSU-Next
        run: |
          TAG="${{ github.event.inputs.ksu_tag || 'v3.1.0-legacy-susfs' }}"
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s "$TAG"

      - name: Setup SUSFS
        run: |
          git clone --recursive https://gitlab.com/simonpunk/susfs4ksu.git -b kernel-4.19 susfs4ksu --depth=1
          cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch KernelSU-Next/
          cp susfs4ksu/kernel_patches/50_add_susfs_in_kernel-4.19.patch ./
          cp susfs4ksu/kernel_patches/fs/* fs/
          cp susfs4ksu/kernel_patches/include/linux/* include/linux/
          cd KernelSU-Next && patch -p1 < 10_enable_susfs_for_ksu.patch && cd ..
          patch -p1 < 50_add_susfs_in_kernel-4.19.patch

      - name: Configure defconfig
        run: |
          # KernelSU
          echo "CONFIG_KSU=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_CMDLINE=1" >> arch/arm64/configs/$KERNEL_CONFIG
          # KPROBES
          echo "CONFIG_MODULES=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KPROBES=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_HAVE_KPROBES=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KPROBE_EVENTS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          # SUSFS
          echo "CONFIG_KSU_SUSFS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          # OverlayFS
          echo "CONFIG_OVERLAY_FS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_TMPFS_XATTR=y" >> arch/arm64/configs/$KERNEL_CONFIG
          # DroidSpaces
          echo "CONFIG_SYSCTL=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_SYSVIPC=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_POSIX_MQUEUE=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_UTS_NS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_IPC_NS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_SECCOMP=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_SECCOMP_FILTER=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_CGROUPS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_CGROUP_DEVICE=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_CGROUP_PIDS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_CGROUP_SCHED=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_FAIR_GROUP_SCHED=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_CGROUP_FREEZER=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_CGROUP_NET_PRIO=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_DEVTMPFS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_FW_LOADER=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_FW_LOADER_USER_HELPER=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_FW_LOADER_COMPRESS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NET_NS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_VETH=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_BRIDGE=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NETFILTER=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_BRIDGE_NETFILTER=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NETFILTER_ADVANCED=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NF_CONNTRACK=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_IP_NF_IPTABLES=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_IP_NF_FILTER=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NF_NAT=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NF_TABLES=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_IP_NF_TARGET_MASQUERADE=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NETFILTER_XT_TARGET_MASQUERADE=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NETFILTER_XT_TARGET_TCPMSS=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NF_CONNTRACK_NETLINK=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NF_NAT_REDIRECT=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_IP_ADVANCED_ROUTER=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_IP_MULTIPLE_TABLES=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NF_CONNTRACK_IPV4=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_NF_NAT_IPV4=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "CONFIG_IP_NF_NAT=y" >> arch/arm64/configs/$KERNEL_CONFIG
          echo "# CONFIG_ANDROID_PARANOID_NETWORK is not set" >> arch/arm64/configs/$KERNEL_CONFIG

      - name: Build kernel
        run: |
          export KBUILD_BUILD_USER=jingesui
          export KBUILD_BUILD_HOST=GitHub-Actions
          make -j$(nproc --all) CC=clang O=out ARCH=arm64 \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=$GITHUB_WORKSPACE/gcc-64/bin/aarch64-linux-android- \
            CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/gcc-32/bin/arm-linux-androideabi- \
            $KERNEL_CONFIG
          make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=$GITHUB_WORKSPACE/gcc-64/bin/aarch64-linux-android- \
            CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/gcc-32/bin/arm-linux-androideabi-

      - name: Package AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3 --depth=1
          sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
          sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' AnyKernel3/anykernel.sh
          sed -i 's/IS_SLOT_DEVICE=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          rm -rf AnyKernel3/.git* AnyKernel3/README.md

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3-${{ github.ref_name }}
          path: AnyKernel3/*
